### PR TITLE
Did stuff

### PR DESCRIPTION
**Pull request by CheesyStandards**
I did a thing

### CODE REVIEW

**Comment by scattana** [comment]
Received, thanks! Please re-try and add a text file with your comments to the repository, instead of changing "mnist_simple_with_comments.py"

**Comment by CheesyStandards** [comment]
How do I do that?

**Comment by scattana** [comment]
- Open any text editor and write your name at the top of the file
- "Save As" (make sure you save the file in the location of your repository - i.e. within the MNIST_digit_recognition folder on your computer...also make sure the file type is .txt)
- Follow the same Git steps to "add" your new file to your local repository, "commit" your local changes, and "push" your local changes to your remote repository
- Create a pull request just like you did before!

**Comment by CheesyStandards** [comment]
What do I name the new file?

**Comment by scattana** [comment]
Whatever you'd like! **your_name.txt** or something similar is great

**Pull request closed without merging**
